scombz-utilities/scombz-utilities-react

- src/contents/onDocumentStart.ts
- src/contents/sidemenu.tsx
- src/contents/types/sidemenu.type.ts
- src/contents/util/sideMenuLogic.ts
> とりあえずMenu追加

- src/contents/lms.ts
- src/contents/util/timetable.ts
- 時間割に教室名を表示
Before
After
- 時間割に教室名を表示
一部機能の追加・修正
時間割に教室名を表示するようにしました。
> Timetable customization

- package-lock.json
- package.json
- src/backgrounds/migration.ts
- src/contents/layout.ts
- src/options/components/CustomCSS.tsx
- src/options/components/Editor.tsx
- src/options/index.css
- src/options/index.tsx
- src/settings.ts
> feat: カスタムCSS機能

- src/contents/tasks.ts
> fix: ログイン前のfetchを防止

- locales/en/messages.json
- locales/ja/messages.json
- src/options/components/CustomContainerParent.tsx
- src/options/components/DataOperation.tsx
- src/options/components/RecommendedOptions.tsx
- src/options/components/SimpleOptions.tsx
- src/options/components/WidgetOptions.tsx
- src/options/index.tsx
- 拡張機能設定画面のおすすめ設定タブ内の説明をi18nr対応した
例: 一部機能の追加・修正
> おすすめ設定のi18n対応

- css/side_menu.css
- src/contents/onDocumentStart.ts
> 画面読み込み時のチラつきを軽減

- locales/en/messages.json
- locales/ja/messages.json
- src/contents/components/TimeTable.tsx
- src/contents/util/getLMS.ts
- fetchを使ってLMS時間割を取得する機能
例: 一部機能の追加・修正
> feat: fetchを使ってLMS時間割を取得する機能

- src/backgrounds/migration.ts
- src/contents/components/TimeTable.tsx
> timetableの描画をリファクタリング

- src/background.ts
> migrationをするタイミングをv4へのアップデート時に限定させる

- src/background.ts
- src/backgrounds/onInstalled.ts
- そのまま
例: 一部機能の追加・修正
___
enhancement
___
- `src/background.ts`から`migrate`関数の呼び出しを削除し、`src/backgrounds/onInstalled.ts`に移動しました。
- バージョン4.0.0で専用のランディングページ(`https://scombz-utilities.com/lp/4.0.0`)を開くように変更しました。
- 開発環境ではランディングページを開かないように変更しました。
___
<tr>
<td>
<details> …
> v4.0.0の時は専用LPを開くように変更

- css/min_input_buttons.css
- src/contents/changeReportButton.ts
治ったか確認できないので、お願いします😭
dev版でなく添付のビルド版で確認いただけると🙏
[chrome-mv3-prod.zip](https://github.com/scombz-utilities/scombz-utilities-react/files/15372920/chrome-mv3-prod.zip)
#60 
例: 一部機能の追加・修正
___
Bug fix, Enhancement
___
- レポート入力ボタンのHTML構造を変更し、CSSファイルをリンクしました。
- ボタンに`data-value`属性を追加し、スライダーバーの値設定ロジックを修正しました。
- 新しいCSSファイルを追加し、ボタンとスライダーバーのスタイルを定義しました。
___
<table><thead><tr><th></th><th align="left">Relevant …
> レポート入力ボタンバグ修正 & css適用

- locales/en/messages.json
- locales/ja/messages.json
- src/contents/components/TaskList.tsx
例: 一部機能の追加・修正
___
Enhancement, Documentation
___
- 課題一覧を再取得するためのボタンを追加しました。
- 課題がない場合に「再取得」ボタンを表示するようにしました。
- `reloadTasklist`ボタンのタイトルを国際化対応しました。
- 英語および日本語のロケールファイルに`reloadTaskList`メッセージを追加しました。
___
<tr>
<td>
<details> …
> feat: 課題一覧を再取得するボタンを追加

- src/contents/mouseDownEvent.ts
#69 
例: 一部機能の追加・修正
___
Enhancement
___
- `mousedownClick`関数に`isCtrlKeyPressed`引数を追加し、Ctrlキーが押された状態での左クリックをホイールクリックとして判定する機能を追加しました。
- Ctrlキーの押下状態を追跡するための`keydown`および`keyup`イベントリスナーを追加しました。
- `mousedownClickLMS`関数にも同様の変更を適用しました。
___
<tr>
<td>
<details> …
> ctrl + clickでホイールクリック判定にする

- css/quickmenu.css
- src/contents/course.ts
- src/contents/util/layoutSubject.ts
例: 一部機能の追加・修正
___
Enhancement
___
- `addQuickMenu` 関数を追加し、クイックメニューを実装
- `sortSubjectByOrder` 関数の呼び出し順序を変更し、クイックメニューを正しく表示
- クイックメニュー用のCSSスタイルを追加
___
<tr>
<td>
<details>
<summary><strong>course.ts</strong><dd><code>クイックメニューの追加と関数呼び出し順序の変更</code>&nbsp; …
> feat: courseページにクイックメニューを追加

- src/contents/util/layoutSubject.ts
> feat: 教材を表示切り替え時にanimationを付けた

- css/emails.css
- css/quickmenu.css
- src/contents/course.ts
- src/contents/util/courseLogic.ts
例: 一部機能の追加・修正
___
Enhancement
___
- `copyEmail`関数を追加し、メールアドレスをコピーする機能を実装
- メールアドレスを含む要素に対してコピーとGmailリンクのボタンを生成
- 新しいCSSファイルを追加し、メールリンクとボタンのスタイルを定義
___
<tr>
<td>
<details>
<summary><strong>course.ts</strong><dd><code>`copyEmail`関数のインポートと呼び出しを追加</code>&nb …
> feat: emailをコピーできる機能を追加

- package.json
- src/backgrounds/onInstalled.ts
- src/contents/addOriginalTaskInCourse.tsx
- src/contents/components/AutoComplete.tsx
- src/contents/components/Bus.tsx
- src/contents/components/Calendar.tsx
- src/contents/components/Links.tsx
- src/contents/components/TaskList.tsx
- src/contents/components/TimeTable.tsx
- src/contents/components/UserMemo.tsx
- src/contents/layout.ts
- src/contents/menuWidget.tsx
- src/contents/util/darkModeCSS.ts
- src/options/components/pages/LayoutOptions.tsx
- src/settings.ts
- src/theme.ts
ダークモードを実装した
例: 一部機能の追加・修正
___
Enhancement, Other
___
- ダークモード対応のためのテーマ切り替えロジックを各コンポーネントに追加
- ダークモード用のCSSを追加し、必要に応じて挿入するロジックを追加
- ダークモード設定オプションを追加し、ユーザーが設定できるように変更
- バージョンを`4.0.0`から`4.1.0`に更新
___
</strong></td><td><details><summary>14 files</summary><table>
<tr>
<td>
<details> …
> dark modeの実装

- package-lock.json
- src/contents/components/Bus.tsx
- src/contents/components/Calendar.tsx
- src/contents/components/Links.tsx
- src/contents/components/TaskList.tsx
- src/contents/components/TimeTable.tsx
- src/contents/components/UserMemo.tsx
- ダークモードの色を訂正した
例: 一部機能の追加・修正
___
Bug fix, Enhancement
___
- ダークモードの背景色を修正しました。各コンポーネント（Bus、Calendar、Links、TaskList、TimeTable、UserMemo）で色コードを`#333848cc`から`#333840cc`に変更しました。
- `package-lock.json`のバージョンを4.0.0から4.1.0に更新しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details> …
> fix darkmode color

- README.md
- README,mdを意図がズレない範囲で修正
ドキュメントの微修正
誤字脱字、リンク切れなどの問題を修正しました。
最初から開発するのは怖いので、一度簡単なドキュメントの修正をPRさせていただきます。
こっちでPRするのは初めてで不慣れな点があると思います。何卒ご指導ご鞭撻のほどよろしくお願いいたします。
___
Documentation
___
- Node.jsのバージョンに関する記述を`v20.9.0`から`v20.11.1`に修正
- nodenvインストール手順のリンクを公式リンクと野良記事リンクに修正
- コマンド例のバージョン番号を`v20.9.0`から`v20.11.1`に更新
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Node.jsバージョンとリンクの修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [fix] README.mdの修正

- src/contents/topPageLayout.ts
> TopページにScombZからのお知らせを表示するようにした

- src/contents/components/Bus.tsx
- src/contents/components/Calendar.tsx
- src/contents/components/Links.tsx
- src/contents/components/TaskList.tsx
- src/contents/components/TimeTable.tsx
- src/contents/components/UserMemo.tsx
- src/contents/onDocumentStart.ts
> グラスモーフィズムの透明度を落とした

- src/contents/util/getLMS.ts
- src/contents/util/layoutSubject.ts
例: 一部機能の追加・修正
___
Bug fix
___
- LMSデータ取得時のエラーハンドリングを改善し、`id`属性がない場合のチェックを追加
- `classroom`と`teacher`の取得時にnull安全演算子を使用し、エラーを防止
- クイックメニュー追加時に特定の要素が存在するかチェックを追加
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>getLMS.ts</strong><dd><code>LMSデータ取得時のエラーハンドリング改善</code>&n …
> LMSに「編集可能な授業」がある場合に取得エラーが起きる問題を修正

- src/contents/components/firefoxWidgetStyle.module.css
- src/contents/menuWidget.tsx
- src/contents/util/functions.ts
- src/popup/index.tsx
例: 一部機能の追加・修正
___
Enhancement
___
- `process.env.PLASMO_BROWSER` を `isFirefox()` 関数に置き換え、Firefox 検出ロジックを改善
- Firefox 用のスタイル適用ロジックを修正
- `.widgetContainer` クラスに `max-width: 1200px` を追加し、Firefox ウィジェットの最大幅を設定
___
<tr>
<td>
<details> …
> fix firefox widget css

- README.md
> add Edge badges

- .gitignore
- package-lock.json
- package.json
- src/contents/tasks.ts
例: 一部機能の追加・修正
___
enhancement, dependencies
___
- 新しい関数`resetOriginalTaskList`を追加し、期限切れのタスクをフィルタリングする機能を実装
- `fetchTasks`関数内でタスクリストをリセットする処理を追加
- `publish-browser-extension`パッケージを追加
- バージョンを`4.1.3`に更新
- `publish`スクリプトを追加し、自動ビルドとパッケージングを実行するコマンドを追加
___ …
> 自動アップロードスクリプトを作成

- src/backgrounds/onInstalled.ts
- src/contents/components/TaskList.tsx
> feat: dakmode task color

- src/contents/course.ts
- src/contents/sideMenu.ts
- src/contents/util/courseLogic.ts
例: 一部機能の追加・修正
___
Enhancement
___
- `attachOverflowContents` 関数を新規追加し、LMSページの飛び出る問題を解決。
- `course` 関数内で `attachOverflowContents` を呼び出すように変更。
- `sideMenu` から `attachOverflowContents` の呼び出しを削除。
___
<tr>
<td>
<details> …
> おかしかった処理の位置をリセット

- src/contents/components/TaskList.tsx
- src/contents/util/darkModeCSS.ts
例: 一部機能の追加・修正
___
Bug fix
___
- ダークモードのタスクの背景色と文字色を調整しました。
- 締め切り時間に応じて、背景色を `pink` に変更しました。
- 24時間以内のタスクのフォントウェイトを変更しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>TaskList.tsx</strong><dd><code>ダークモードのタスクの背景色と文字色の調整</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: ダークモードのタスクの背景色等を調整

- src/options/components/pages/AdvancedOptions.tsx
#96 
例: 一部機能の追加・修正
___
Enhancement
___
- `AdvancedOptions.tsx`ファイルから重複していた`CustomSwitch`コンポーネントを削除しました。
- `markdownNotePad`オプションを削除しました。
___
<tr>
<td>
<details>
<summary><strong>AdvancedOptions.tsx</strong><dd><code>重複したオプションの削除</code>&nbsp; &nbsp; …
> 重複オプションの統一

- src/contents/login.ts
例: 一部機能の追加・修正
___
Bug fix, Enhancement
___
- 新しい関数 `getOshirase` を追加し、ログイン前お知らせの取得とデコードを行う処理を実装しました。
- お知らせのHTMLを生成し、ローカルストレージに保存する処理を修正しました。
- エラーハンドリングを追加し、取得失敗時のログを出力するようにしました。
___
<tr>
<td>
<details> …
> ログイン前お知らせの取得がうまく行っていなかったのを修正した

- src/contents/util/courseLogic.ts
レポート提出画面でコンテンツ高さ調整を実行しないようにする
例: 一部機能の追加・修正
___
Bug fix
___
- レポート提出画面では`attachOverflowContents`関数を実行しないように修正
- `location.href`をチェックし、特定のURLパターンに一致しない場合は関数を早期リターンする条件を追加
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>courseLogic.ts</strong><dd><code>`attachOverflowContents`関数の実行条 …
> レポート提出画面でコンテンツ高さ調整を実行しないようにする

- css/top_page_layout.css
- package.json
- src/contents/components/TaskList.tsx
- src/contents/innerPageTaskList.tsx
- src/contents/topPageLayout.ts
- src/contents/util/color.ts
- src/contents/util/getRelativeTime.ts
例: 一部機能の追加・修正
___
enhancement
___
- `TaskList.tsx`コンポーネントをリファクタリングし、`getTaskColor`と`getRelativeTime`のユーティリティ関数を使用。
- 新しい`innerPageTaskList.tsx`コンポーネントを追加し、課題リストを内部ページに表示。
- `topPageLayout.ts`に新しいID属性を追加してレイアウトを更新。
- `getTaskColor`と`getRelativeTime`関数をそれぞれのユーティリティファイルに移動。
- 課題リスト表示のためのCSSスタイルを追加。
- パッケージバージョンを4.1.5から4.2.0に更新。
___
<table><thead><tr><th></th><th align="left">Relevant …
> Topページに課題一覧を表示

- css/addTaskButton.css
- locales/en/messages.json
- package.json
- src/contents/addOriginalTaskInCourse.tsx
例: 一部機能の追加・修正
___
enhancement, bug fix
___
- 自作課題追加ボタンにタイトル属性を追加し、アクセシビリティを向上させました。
- CSSでボタンの位置を左から右に変更しました。
- 自作課題追加のメッセージを更新しました。
- バージョンを4.2.0から4.2.1に更新しました。
___
<tr>
<td>
<details>
<summary><strong>addOriginalTaskInCourse.tsx</strong><dd><code>Add …
> fix: 自作課題追加ボタンの位置を修正

- src/contents/components/originalClassModal.tsx
> 科目が多い時にスクロールに変化するように変更

- css/class_survey_button.css
- src/contents/components/TaskList.tsx
- src/contents/components/menuWidgetFirefox.tsx
- src/contents/innerPageTaskList.tsx
- src/contents/util/courseLogic.ts
- src/contents/util/darkModeCSS.ts
- src/options/components/pages/BasicOptions.tsx
- src/options/components/pages/WidgetOptions.tsx
- src/options/container/firefox.tsx
- src/popup/index.tsx
- src/settings.ts
> アンケート全表示機能を追加

- src/contents/util/darkModeCSS.ts
- src/options/components/blocks/OptionGroup.tsx
- src/options/components/pages/WidgetOptions.tsx
- src/options/container/chrome.tsx
> オプションページのダークモード対応

- package.json
- src/contents/innerPageTaskList.tsx
> トップページの並び替え順序変更

- locales/en/messages.json
- locales/ja/messages.json
- src/options/components/blocks/CustomTextField.tsx
- src/options/components/pages/BasicOptions.tsx
- src/options/container/chrome.tsx
> 強制的に保存できるようにした

- package.json
- src/contents/login.ts
- src/contents/util/adfsLogic.ts
> お知らせの修正と、ログイン失敗時の無限ループ修正

- src/contents/sgsot.ts
> secureではないURLを追加した

- package.json
- src/background.ts
- src/contents/sicWeb.ts
- src/contents/syllabus.ts
> キャッシュクリア機能の追加

- src/backgrounds/badge.ts
- src/popup/index.tsx
> バッジの色を変更 / popup開くたびに色を再設定

- .env.local.template
- afterBuild.py
- package.json
- src/background.ts
- src/backgrounds/badge.ts
- src/backgrounds/google.ts
- src/contents/components/TaskList.tsx
- src/contents/innerPageTaskList.tsx
- src/contents/tasks.ts
- src/contents/types/task.d.ts
- src/options/components/blocks/LoginToGoogle.tsx
- src/options/components/pages/BasicOptions.tsx
- src/popup/index.tsx
- src/settings.ts
> Google Classroom連携機能

- package.json
- src/backgrounds/google.ts
- src/contents/tasks.ts
- src/contents/types/task.d.ts
- src/contents/util/getTaskList.ts
- src/options/components/pages/BasicOptions.tsx
> Classroom関連の修正

- css/new_report_button.css
- css/submission.css
- locales/en/messages.json
- locales/ja/messages.json
- src/backgrounds/migration.ts
- src/contents/submission.ts
- src/contents/util/courseLogic.ts
- src/contents/util/darkModeCSS.ts
- src/options/components/pages/AdvancedOptions.tsx
- src/options/container/firefox.tsx
- src/settings.ts
> ファイル複数提出の実装
